-- 코드를 입력하세요
SELECT *
FROM (SELECT UG.USER_ID, UG.NICKNAME, SUM(UB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UB
LEFT OUTER JOIN USED_GOODS_USER UG
ON UB.WRITER_ID = UG.USER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY UB.WRITER_ID
ORDER BY TOTAL_SALES ASC) AS T
WHERE T.TOTAL_SALES >= 700000
;
-- sql if else 문
//다른사람 풀이 
-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;
