-- 코드를 작성해주세요
SELECT 
    A.ID,
    COUNT(B.ID) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT OUTER JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID
GROUP BY A.ID
;
-- ORDER BY ID
-- Null 있는 컬럼은 GROUP BY 하면 오류남..

-- 코드를 작성해주세요
SELECT ID,
CASE WHEN SIZE_OF_COLONY>1000 THEN 'HIGH'
WHEN SIZE_OF_COLONY>100 AND SIZE_OF_COLONY<1000 THEN 'MEDIUM'
WHEN SIZE_OF_COLONY<=100 THEN 'LOW'
END AS SIZE
FROM ECOLI_DATA
;